"""remove chat_id field from messageg table

Revision ID: 7611f78d0fe2
Revises: 82ab3217e86b
Create Date: 2025-05-14 18:34:27.153580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7611f78d0fe2'
down_revision: Union[str, None] = '82ab3217e86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
