"""add messages table

Revision ID: 82ab3217e86b
Revises: 374512e8c82c
Create Date: 2025-05-14 18:17:46.380772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ab3217e86b'
down_revision: Union[str, None] = '374512e8c82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['scenario_states.id'], name=op.f('fk_messages_state_id_scenario_states'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.add_column('polls', sa.Column('state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_polls_state_id_scenario_states'), 'polls', 'scenario_states', ['state_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_polls_state_id_scenario_states'), 'polls', type_='foreignkey')
    op.drop_column('polls', 'state_id')
    op.drop_table('messages')
    # ### end Alembic commands ###
